version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: qes_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: qes
            MYSQL_USER: qes
            MYSQL_PASSWORD: qes

    php:
        build: .docker/php
        container_name: qes_php
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/qes
        depends_on:
          - mysql
        environment:
          - MYSQL_URL=mysql

